### ISSUE TITLE
Reworked Items

### ISSUE THREAD

**Issue by NiHoel** [Miraak7000/AssetViewer#14]
The changes of Fenja, leading elictrical engineer and Magnetist (extra good oil removed) seem not to be reflected in the update.

**Comment by Veraatversus** [comment]
can you send a ingame screenshot of these items? i have checked these two guys and i havn't found any bugs. seems ok for me and the extra oil is still ingame.

**Comment by NiHoel** [comment]
Entschuldigung, ich hatte noch nicht mitbekommen, dass sie das mit dem Öl doch noch gefixt haben.
