### ISSUE TITLE
Advanced Filter option ≠ is not working correctly

### ISSUE THREAD

**Issue by daish0** [Miraak7000/AssetViewer#21]
Hi,

when filtering in _Improvements_ assets for _Source_ and selecting e.g. _Quest - Farmer_ you get all rewards for farmer quests. Then adding e.g. _Animal Farm_ as specific Quest to filter.

But when you switch from the equal sign = to ≠, the resulting selection doesn't change.

I tried to filter out e.g. "common items" (items that have a lot of or easy ways to aquire) with this method to only show very hard-to-get items, but it doesn't really work that way.

Thanks and best regards,
daish0

**Comment by Veraatversus** [comment]
I think now you get the expected results for your filter. You can download the fixed version under https://drive.google.com/open?id=1N5AUPYDhhluKMLPEMvF45qsUs27ed6Cg and it will be included in the next release. thanks for the report.

**Comment by Veraatversus** [comment]
and i think know it would be better for you when you leave the first field blank, than only the pure quest name is filtered no matter of the quest giver linke that: http://bit.ly/32nksk2

**Comment by daish0** [comment]
Hi, it seems to work very good now, thanks - that is a huge improvement.
