### ISSUE TITLE
Advanced filter options are not working properly anymore

### ISSUE THREAD

**Issue by Hippo137** [Miraak7000/AssetViewer#26]
Filtering anything with the advanced filters works... until you add a comparison. If for example you filter for the Attribute Accuracy, you get four items. If you then choose a comparison operator (for example =) and then choose a value, you are offered the four different available accuracy values (working properly so far, first image). If you select one though, the results are independent on the chosen attribute. For example choosing “Attribute Accuracy = +100%” doesn’t find all items which have +100% accuracy (which is only one in this case), but it finds all items which have any +100% in them (second image).
To get it working, you have to select the Attribute at the top, too (image 3).

This wasn‘t the case in ... whatever version I had before (downloaded 11th december) (image 4).

![image](https://user-images.githubusercontent.com/60151839/77858087-862f4500-7201-11ea-8bbe-30265d7cace5.png)

![image](https://user-images.githubusercontent.com/60151839/77858053-63049580-7201-11ea-8662-afca0336dd13.png)

![image](https://user-images.githubusercontent.com/60151839/77858130-bf67b500-7201-11ea-84ea-b4c412a935e0.png)

Comparison (older working version):
![image](https://user-images.githubusercontent.com/60151839/77858074-757ecf00-7201-11ea-8a3a-cd8223f44332.png)

**Comment by Veraatversus** [comment]
yes its a bug not an feature and its fixxed. thanks for report.
