### ISSUE TITLE
Wrong Information for "Rabies Vaccine" 

### ISSUE THREAD

**Issue by StingMcRay** [Miraak7000/AssetViewer#29]
Dear reader, 

I think the Rabies Vaccine has the wrong information (maybe they changed it on GU7)
This is the info that comes with it : 
![Screenshot_7](https://user-images.githubusercontent.com/18048706/78156401-0c849a80-743f-11ea-9c7b-1d6fe886a8d1.png)

Regards
Sting McRay

**Comment by Veraatversus** [comment]
should working now for a couple of items.
