### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by Maxa-S** [Miraak7000/AssetViewer#30]
Добавьте русский язык.
Спасибо.

**Comment by Veraatversus** [comment]
sry i cant speak russia. if you can translate the following sentences i will do this.

{
  "0": "",
  "-1": "Trait: ",
  "-3": "Quest",
  "-4": "Tourism",
  "-5": "Expedition completed",
  "-6": "Early Game",
  "-7": "Early-Mid Game",
  "-8": "Mid Game",
  "-9": "Late-Mid Game",
  "-10": "Late Game",
  "-11": "End Game",
  "-12": "Ship Drop",
  "-101": "Asset",
  "-102": "Improvements",
  "-105": "World Fair",
  "-106": "Equipped in",
  "-109": "Level",
  "-110": "Third Party",
  "-120": "Expedition Events",
  "-130": "Buildings",
  "-1001": "Rarity",
  "-1002": "Type",
  "-1003": "Affects Building Group",
  "-1004": "Search",
  "-1005": "Source",
  "-1006": "Attribute",
  "-1007": "Patch Version",
  "-1008": "Detailed Sources",
  "-1023": "Rarity",
  "-1048": "Progression",
  "-1049": "Player",
  "-1100": "Reset Filters",
  "-1101": "Only available items ",
  "-1102": "Affects Building",
  "-1103": "Sort by",
  "-1104": "Advanced Filters",
  "-1105": "Buildable only ",
  "-1200": "Name",
  "-1201": "ID",
  "-1210": "Affects ",
  "-1220": "Expeditions-Bonus",
  "-1221": "Part of set",
  "-1230": "No Allocation",
  "-1240": "Main Island",
  "-1241": "Secondary Islands"
}

**Comment by Maxa-S** [comment]
У многих слов по несколько значений, плюс смысловая нагрузка.
Постарался наиболее точно подобрать смысл.
" * " нашёл в программе, подобрал по смыслу (надеюсь).
" ? "не нашёл в программе, просто перевод. (или не понял цель фильтра)

{
"0": "",
"-1": "Черта:", ?
"-3": "Квест", *
"-4": "Привлекательность", ?
"-5": "Экспедиция завершена", ?
"-6": "Ранняя игра", *
"-7": "Игра ранней середины", *
"-8": "Середина игры", *
"-9": "Игра поздней середины", *
"-10": "Поздняя игра", *
"-11": "Конец игры", *
"-12": "Добыча с корабля", ?
"-101": "Имущество", ?
"-102": "Улучшения", ?
"-105": "Всемирная ярмарка", *
"-106": "Оборудовано в", *
"-109": "Уровень", *
"-110": "НПС товары", ?
"-120": «Экспедиционные квесты, *
"-130": "Здания", *
"-1001": "Редкость", *
"-1002": "Тип", *
"-1003": "Влияет на строительную группу", *
"-1004": "Поиск", *
"-1005": "Ключ", ?
"-1006": "Атрибуты", *
"-1007": "Патч-версия", *
"-1008": "Подробные источники", ?
"-1023": "Редкость", *
"-1048": "Этап игры", *
"-1049": "Игрок", *
"-1100": "Сбросить фильтры", *
"-1101": "Только доступные предметы", *
«-1102»: «Влияет на здание», *
"-1103": "Сортировать по", *
«-1104»: «Расширенные фильтры», *
"-1105": "Только для сборки", ?
"-1200": "Имя", *
"-1201": "ID", *
"-1210": "Влияет", ?
"-1220": "Бонус Экспедиции", *
"-1221": "Часть набора", *
"-1230": "Нет распределения", ?
"-1240": "Главный остров", ?
"-1241": "Вторичные острова" ?
}

**Comment by Veraatversus** [comment]
thx for translation. its implemented and released.
