### ISSUE TITLE
New version 5.1 would not start up 

### ISSUE THREAD

**Issue by StingMcRay** [Miraak7000/AssetViewer#32]
As you have an update to 5.1, the Exe file does not start up

**Comment by Veraatversus** [comment]
pls try to redownload it. dont know whats the problem. i have reuploaded it and hope it works for you too

**Comment by Veraatversus** [comment]
thanks for the hint

**Comment by StingMcRay** [comment]
No worries @Veraatversus 
Btw, can you add a version info to your exe file so we know what version we running ?

**Comment by StingMcRay** [comment]
ow, and the new uploaded version does work

**Comment by StingMcRay** [comment]
Thanks, see you around 
*closing Issue*
