### ISSUE TITLE
Any way of exporting the lists with id's to a xml or txt file?

### ISSUE THREAD

**Issue by iksaandry** [Miraak7000/AssetViewer#35]
If there was a way to export it, it would certainly make it easier to mod the game.

**Comment by Veraatversus** [comment]
Currently, without writing 1 line of code yourself, not.
What exactly do you imagine?

**Comment by iksaandry** [comment]
Just a simple way of either copying to the clipboard the filtered list of items or export them to a comma separated txt file containing all ID's and names.

**Comment by Veraatversus** [comment]
you have to select at least on item in the list (thats the list has focus) and then press ctrl C to copy paste the whole filtered list. example output are :
191980 Bauwerkzeug,191882 Dekes unentbehrliche Werftkiste,191436 Feldmarschall Matravers, Armeeführer,191979 Schreinerwerkzeug,191881 Werftwerkzeugsystem

download in the prerelease channel: https://drive.google.com/open?id=1N5AUPYDhhluKMLPEMvF45qsUs27ed6Cg

**Comment by iksaandry** [comment]
That's perfect! Thank you very much!

**Comment by iksaandry** [comment]
The mod I was working on that ended up being finished much faster thanks to your help. 
https://github.com/iksaandry/anno_1800_all_slotables_unlocked_at_traders
