### ISSUE TITLE
Update to v14 (latest Version) & latest DLC "Keim der Hoffnung"

### ISSUE THREAD

**Issue by matthiasballreich** [Miraak7000/AssetViewer#46]
Ist ein Update auf das neuste Game-Update und DLC "Keim der Hoffnung" geplant?

**Comment by Veraatversus** [comment]
Danke für die Erinnerung. Ja ein Update ist geplant, jedoch muss ich aufgrund meiner Nachlässigkeit erst einmal noch das update 13 nachholen. Die Arbeiten daran habe ich nun mittlerweile schon begonnen, jedoch bin ich schwer beschäftigt. Ich denke somit nächste Woche ist mit dem fertigen Update zu rechnen.

**Comment by Veraatversus** [comment]
done

**Comment by Veraatversus** [comment]
hmm ka schau ich mir nochmal an. vielen dank für die info

**Comment by matthiasballreich** [comment]
Sind noch mehr die fehlen. Alle aus dem Szenario "der silberne Käfig", also sowas wie silbererz, koks, cyanid, silberamalgam, etc.

Aus dem Szenario "Ende von Eden" ist Herbarium drin, der rest, wie Stromkabel, Werkzeug, etc. nicht

Aus dem DLC "Keim der Hoffnung" fehlt u.a. Chilisauce.

Atole habe ich auch nicht gefunden.

Ist nur einer kleine beispielhafte Übersicht was u.a. fehlt. Hab nicht alles vorliegen ;)

**Comment by Veraatversus** [comment]
wenn du den haken raus nimmst "alle verfügbaren items" findest du eine ecke mehr items. jedoch ist das nicht die lösung des problems. ich habe das release ersteinmal wieder zurückgezogen und muss mich die tage erneut mit den szenario files auseinandersetzen. die sind etwas anders strukturiert und da muss ich erst noch nach einer lösung schauen. sry aber dann dauerts noch etwas.

**Comment by Veraatversus** [comment]
Die dinge die fehlen sind Alles Produkte und keine Items richtig?

**Comment by matthiasballreich** [comment]
sieht so aus. Zumindest konnte ich das bei den Waren feststellen. Items scheinen da zu sein. Konnte die aber nicht wirklich näher prüfen. Bei den paar Stichproben sah es aber gut aus

**Comment by Veraatversus** [comment]
Die Szenarien haben mir einige Probleme bereitet und ich hoffe ich habe diese nun zufriedenstellend gelöst. Neues Release ist damit verfügbar.
