### ISSUE TITLE
Mehrere Text Suchfilter sind buggy

### ISSUE THREAD

**Issue by Veraatversus** [Miraak7000/AssetViewer#51]
Wenn mehrere Suchfilter genutzt werden kann jeweils nur 1 buchstabe eingegeben werden. Sie können nicht mehr gelöscht werden und sie filtern nicht wie gewünscht.

**Comment by Origitalus** [comment]
Bei mir das selbe. 
Die Filterung funktioniert aber schon.

**Comment by Veraatversus** [comment]
Changed the behavior of the text bars. So hopefully all is fixxed.
Thanks for report.
