### ISSUE TITLE
Get Rich Quick Vol VI has wrong name in German language!

### ISSUE THREAD

**Issue by Origitalus** [Miraak7000/AssetViewer#53]
Hi, first of all thank you for this great tool, and now to the bug report:
The Volume of this Item is "IV" instead of "VI"

Also, if I search with "iv", the German Version finds everything, but the English Version doesn't; only when I search "vol iv". Weeiird.

Thanks. 
Bye.

**Comment by Veraatversus** [comment]
The name of the items are based on item id and come direktly from the anno files. There may be a bug in this files from anno maybe.
Thanks for report.
