### ISSUE TITLE
Feature request: Search not limited to titles

### ISSUE THREAD

**Issue by Origitalus** [Miraak7000/AssetViewer#54]
Can you not limit the search to the Item titles but also to the description/or part of the description?
For example I would like to search for Town Hall items which provide fish. 
But when I choose the attribute "provided needs" and search for "fish" only two items are shown: "Cauldron of Fish Stew" and "Tinned Fish". The third item would be "Sunday Roast", but it isn't shown because it doesn't have fish in its title.

**Comment by Origitalus** [comment]
OH never mind! I just have to put under Advanced Filters: Attribute "Provided Needs" = "Fish" and BÄM. 
Thanks.

**Comment by Veraatversus** [comment]
So hopefully is fixxed ;)
Thanks for report.
