### ISSUE TITLE
Bugreport: Chosen field values disappear from sight but are still active after searching and not finding.

### ISSUE THREAD

**Issue by Origitalus** [Miraak7000/AssetViewer#55]
So if I for example choose the attribute "Extra Goods" and then I type in the searchbox "fish", the AssetViewer removes the "Extra Goods" from the Attributes field, which it shouldn't.

**Comment by Veraatversus** [comment]
Changed the behavior of the text bars. So hopefully all is fixxed.
Thanks for report.
