### ISSUE TITLE
Goldschmied Gilbert und Illustrer Gemologe wrong Text

### ISSUE THREAD

**Issue by Origitalus** [Miraak7000/AssetViewer#56]
Goldschmied Gilbert und Illustrer Gemologe say "Goldbarre => Gold", which should be the other way around.

**Comment by Veraatversus** [comment]
In the gamefiles it is written exactly how it is in the assetviewer.
![Code_LXct8TfxWf](https://user-images.githubusercontent.com/11431526/192112758-baaf1c0d-4bbf-4f2d-87b5-b046cf858111.png)

It is really a bug?
Thanks for report.

**Comment by Origitalus** [comment]
No, I was wrong. All good.
