### ISSUE TITLE
"Extra goods" ratios are backwards

### ISSUE THREAD

**Issue by ErenBikmaz** [Miraak7000/AssetViewer#57]
items such as "the country bumpkin cigar roller" advertise extra items as 25/1 instead of 1/25
![ratio](https://user-images.githubusercontent.com/50349469/185734087-8fb0179f-a689-406a-96cb-58b438e04b10.PNG)

**Comment by Origitalus** [comment]
I don't think that's backwards. Or are you seriously telling me that this item produces 25 extra cigars per cycle?^^
Notice that almost all the Extra Goods items have this format: "<big number> / 1" 
The exception being the "Extra Virgin Oily Sucker" and "Super Oily Sucker", which give 1/4 and 2/4. 
Here's a good overview https://anno1800.fandom.com/wiki/Oil?so=search#Extra_Oil_from_Oil_Wells,_Mines_and_Quarries

**Comment by Veraatversus** [comment]
Have changed it with the update 15 version.
Thanks for report.
