### ISSUE TITLE
Question about using parts of your software

### ISSUE THREAD

**Issue by noX1609** [Miraak7000/AssetViewer#6]
Hi,

first i want to say: I‘ts not really an issue with the app but didn‘t find another way to contact you so hope it‘s ok i‘m writing it here.

don‘t know which language you are able to understand so i try it with english (my native language is German so sooty for my english skills ;))
I really like your Program it already helped me a lot of times.
Because i always have my iPad around and no second screen i would be happy to be able to use it with that.
If i saw correctly there isn‘t already an App so i thought (because i learned how to code in Swift) will do an App for my one and maybe publish it. Because i would like to use the xml files provided in your tool i wanted to ask for your permission to use them and also publish them included in the App in the AppStore (of cause it will be free so i din‘t want to take a part of your work (the .xml files and maybe some parts of the cs code) and make money out of it). Of cause i will give credit to you inside the app.

Would that be ok for you?

Thanks in advance for your answer.

Greetings
Marc

**Comment by Veraatversus** [comment]
Ich denke da sollte es keine Probleme geben und du kannst deine arbeit beginnen. 
wenn es Probleme oder fragen zum code oder den Xmls gibt nur zu ;)
habe selbst schon über eine android app nachgedacht, bin mir aber noch nicht ganz sicher.
momentan habe ich noch mit anderen Projekten zutun.
