### ISSUE TITLE
Missing Building.

### ISSUE THREAD

**Issue by Qurila** [Miraak7000/AssetViewer#61]
It seems that the residence of the Eldesr 114437 is not listed.

![image](https://user-images.githubusercontent.com/106919838/192525728-177c03ec-9dae-4880-9ad8-d3df168af3e7.png)

**Comment by Veraatversus** [comment]
There is when you uncheck the Buildable only filter.
The Filter checks only if the building has Construction Costs and the residence of the Eldesr seems to be has no construction costs or this is the actual bug?
